export const stockCodesAmerique: Record<string, Record<string, string>> = {
  'Consommation discrétionnaire': {
    'AMZN': 'AMAZON',
    'TSLA': 'TESLA',
    'NKE': 'NIKE',
    'DG': 'DOLLAR GENERAL',
    'PVH': 'PVH',
    'NWL': 'NEWELL BRANDS',
    'FAST': 'FASTENAL',
    'SHW': 'SHERWIN-WILLIAMS ',
  },
  'Consommation de base': {
    'PG': 'PROCTER & GAMBLE',
    'KO': 'COCA COLA',
    'WMT': 'WALMART',
    'CVS': 'CVS HEALTH',
    'TSN': 'TYSON FOODS',
    'HRL': 'HORMEL FOODS',
    'KHC': 'THE KRAFT HEINZ',
  },
  'Santé': {
    'JNJ': 'JOHNSON & JOHNSON',
    'PFE': 'PFIZER',
    'UNH': 'UNITEDHEALTH GROUP',
    'BAX': 'BAXTER INTL',
    'HUM': 'HUMANA',
    'BMY': 'BRISTOL-MYERSSQU',
    'LLY': 'ELI LILLY & CO',
    'ABT': 'ABBOTT LABORATOR',
    'MEDP': 'MEDPACE HOLDINGS',
  },
  'Industries': {
    'CAT': 'CATERPILLAR',
    'GE': 'GENERAL ELECTRIC',
    'MMM': '3M',
    'DAL': 'DELTA AIR LINES',
    'GGG': 'GRACO',
    'ROK': 'ROCKWELL AUTOMAT',
    'ARW': 'ARROW ELECTRONIC',
    'TEX': 'TEREX CORP',
  },
  'Énergie': {
    'XOM': 'EXXONMOBIL',
    'CVX': 'CHEVRON',
    'COP': 'CONOCOPHILLIPS',
    'NOV': 'NOV',
    'WEC': 'WEC ENERGY GROUP ',
    'IDA': 'IDACORP',
  },
  'Matériaux': {
    'DOW': 'DOW INC.',
    'NEM': 'NEWMONT CORPORATION',
    'MLM': 'MARTIN MARIETTA',
  },
  'Services aux collectivités': {
    'DUK': 'DUKE ENERGY',
    'NEE': 'NEXTERA ENERGY',
    'SO': 'SOUTHERN COMPANY',
  },
  'Finance': {
    'JPM': 'JPMORGAN CHASE',
    'BAC': 'BANK OF AMERICA',
    'GS': 'GOLDMAN SACHS',
    'V': 'VISA',
    'PYPL': 'PAYPAL',
    'MA': 'MASTERCARD',
    'BRK.B': 'BERKSHIRE HATHAWAY RG-B',
    'WFC': 'WELLS FARGO',
    'C': 'CITIGROUP',
    'MS': 'MORGAN STANLEY',
    'AXP': 'AMERICAN EXPRESS',
    'SCHW': 'CHARLES SCHWAB',
  },
  'Immobilier': {
    'AMT': 'AMERICAN TOWER CORPORATION',
    'PLD': 'PROLOGIS',
    'EQIX': 'EQUINIX',
  },
  'Technologie': {
    'NVDA': 'NVIDIA',
    'AAPL': 'APPLE',
    'MSFT': 'MICROSOFT',
    'MSTR': 'MICROSTRATEGY',
    'QCOM': 'QUALCOMM',
    'CRM': 'SALESFORCE',
    'MU': 'MICRON TECHNOLOGY',
    'SWKS': 'SKYWORKS',
    'CTSH': 'COGNIZANT TECH',
    'MSI': 'MOTOROLA SOLTN',
  },
  'Services de communication': {
    'VZ': 'VERIZON COMMUNICATIONS',
    'META': 'META',
    'GOOGL': 'ALPHABET',
    'T': 'AT&T',
    'TMUS': 'T-MOBILE US',
  },
};
